name: test
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.6
  
  # Firebase packages
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  
  # Icons packages
  eva_icons_flutter: ^3.1.0
  animated_icon: ^0.0.9
  panara_dialogs: ^0.1.5
  flutter_facebook_auth: ^7.1.0
  awesome_dialog: ^3.2.1
  flutter_animated_dialog: ^2.0.1
  simple_animated_icon: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  # Assets
  assets:
    - images/
  
  # Fonts (if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
